LoginPage=Change password
legend=Change Your password here
Username=Previous password
UserName_Tip=Enter your previous password here.
UserName_Help=Make sure to use Previous password
Passwrd=New password
Password_Tip=Enter new password here
Password_Help=Make sure to have letters and numbers in your password.
Submit_btn=change password
FixPassword=Reset password
Graphic=none
GraphicAlt=Alt text goes here