LoginPage=Login
legend=I have edited this html file
Username=UserName
UserName_Tip=Enter your user name
UserName_Help=Your user name is your email.
Passwrd=You Password
Password_Tip=Enter your password
Password_Help=Keep your passord private!
Submit_btn=Submit
FixPassword=Reset your password
Graphic=none
GraphicAlt=Alt text describes an image file. There is no actual image file.