LoginPage=Login
legend=I have edited thisssssssssssssssssssss html file.
Username=User Namell
UserName_Tip=Enter your user name here.
UserName_Help=Your user name is your email.
Passwrd=Your Password
Password_Tip=Enter your password
Password_Help=Keep your passord private!
Submit_btn=Submit
FixPassword=Reset your password.
Graphic=none
GraphicAlt=Alt text usually describes an image file. There is no actual image file to describe here.
