LoginPage=Change Password
legend=Something witty here
Username=Current Password
UserName_Tip=Enter your current password
UserName_Help=Your current password is your current password.
Passwrd=New password
Password_Tip=Enter New password
Password_Help=Keep your passord private.
Submit_btn=Submit
FixPassword=Reset passwrd
Graphic=none
GraphicAlt=Alt text goes here