LoginPage=Answer you my questions two...
legend=...ere the other side you'll view.
Username=UserName
UserName_Tip=WHAT. is your name?
UserName_Help=Your user name is your username.
Passwrd=Password
Password_Tip=WHAT. is your favourite colour?
Password_Help=Keep your password private.
Submit_btn=Submit
FixPassword=I forgot my password again...
Graphic=images/KRoCbng.png
GraphicAlt=Alt text goes here