 LoginPage=Daniel's Login Page
legend=HTML is cool ain't it?
Username=UserName
UserName_Tip=Enter your cool user name here bro.
UserName_Help=Your user name is your name for a user.
Passwrd=Password
Password_Tip=Enter the password, obviously.
Password_Help=Keep your passord secure.
Submit_btn=Submit
FixPassword=Whoops, you forgot your password.
Graphic=none
GraphicAlt=There is no image, duh.