LoginPage=Login
legend=Super Woman
Username=Martimar
UserName_Ms T.Fox
UserName_Help==Who is the Queen>??
Passwrd=Bring it Home
Password_Tip=M@moune1012
Password_Help=Put your password in a safe place.
Submit_btn=Pass it in
FixPassword=Change your password
Graphic+0
GraphicAlt=Alt bring it home