LoginPage=Robert Log In
legend=Reversal of Fortune
Username=Password
UserName_Tip=Enter your password
UserName_Help=12345 is the most secure password
Passwrd=Username
Password_Tip=Enter your username
Password_Help=Post your password publicly
Submit_btn=De
FixPassword=Wea
Graphic=images
GraphicAlt=Th
