LoginPage=Roberts Login Page2
legend=Reversal of fortune
Username=Password
UserName_Tip=Enter your password
UserName_Help=12345 is the most secure password
Passwrd=Username
Password_Tip=Enter your user name
Password_Help=Post your password publicly
Submit_btn=Delete
FixPassword=Wear Goggles
Graphic=imageshelp.png
GraphicAlt=This page is anti-star
