LoginPage=Login
legend=This is intentionally confusing
Username=Password
UserName_Tip=Enter password
UserName_Help=12345 is the most secure password
Passwrd=UserName
Password_Tip=Enter user name
Password_Help=Try 'default user' if you forget
Submit_btn=Delete
FixPassword=Free money
Graphic=images/help.png
GraphicAlt=I did this wrong on purpose