LoginPage=Login Page
legend=Legend
Username=User name
UserName_Tip=Enter your user name
UserName_Help=Clever help goes here
Passwrd=Password
Password_Tip=Enter password
Password_Help=No sharing passwords
Submit_btn=Log ing
FixPassword=Reset password
Graphic=images/Star.png
GraphicAlt=This is a cool star image
